### ISSUE TITLE
支持vue3.0

### ISSUE THREAD

**Issue by liguoye** [theshying/vue-print#6]
作者  您好  请问可以支持vue3吗

**Comment by theshying** [comment]
支持

**Comment by liguoye** [comment]
您好   这是我在vue3.0中引用后报错   install中找不到vue的实列  麻烦您指正一下 谢谢
![image](https://user-images.githubusercontent.com/27951326/121002982-8e98ed80-c7bf-11eb-81cd-99e665d7ec12.png)
![image](https://user-images.githubusercontent.com/27951326/121003030-9eb0cd00-c7bf-11eb-9b63-1cd6bfab5e0f.png)
